project:
  type: book
  output-dir: docs

book:
  title: "Understanding Knee Strength during ACLR Recovery"
  author: "Oliver Meek, Tara Udani, Carrie Feng"
  date: "5/6/2025"
  favicon: knee.png
  sidebar:
    logo: knee.png
    search : true
  description: "Exploring Flexion and Extension Post Surgery."
  repo-url: https://github.com/MeekButMighty/finalproj


  chapters:
    - index.qmd
    - datacleaning.qmd
    - eda.qmd
    - dataviz.qmd
    - datadictionary.qmd


format:
  html:
    theme: light
    code-fold: false
    backgroundcolor: "#ffffff"



